/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/clerk'
    | '/demo/tanstack-query'
    | '/room/$roomId'
    | '/demo/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/clerk'
    | '/demo/tanstack-query'
    | '/room/$roomId'
    | '/demo/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/demo/clerk'
    | '/demo/tanstack-query'
    | '/room/$roomId'
    | '/demo/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
